
version: 2

models:
    - name: customer-purchases-test-af
      description: "Customer list with total order value, count and days since last purchase"
      columns:
          - name: CustomerId
            description: "The primary key for the Customer"
            tests:
                - unique
                - not_null
    - name: sales-series-test-af
      description: "Total sales by (ascending) date"
      columns:
          - name: SalesDate
            description: "The primary key for the Customer"
            tests:
                - unique
                - not_null
