
version: 2

models:
    - name: customer-orders
      description: "Customer list with total order value"
      columns:
          - name: CustomerId
            description: "The primary key for the Customer"
            tests:
                - unique
                - not_null
    - name: product-city-sales
      description: "Total sales by product and by city"
      columns:
          - name: ProductId
            description: "The primary key for the Product"
            tests:
                - not_null
          - name: EAN
            description: "The EAN for the Product"
            tests:
                - not_null
    - name: sales-series
      description: "Total sales by (ascending) date"
      columns:
          - name: SalesDate
            description: "The primary key for the Customer"
            tests:
                - unique
                - not_null
