version: '2.1'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    
    volumes:
      - ..:/usr/src/challenge
    
    ports:
     - 8080:8080
     - 8081:8081

    env_file:
     - ../uncommitted/cred/dc-docker.env
    
    # Custom DNS makes makes sure that containers keep working when switching networks on your host
    dns:
     - 8.8.8.8
     - 8.8.4.4
    
    # Limit memory
    mem_limit: 2000m
    memswap_limit: 2000m
    tty: true